package com.indianservers.iqlabs.model

internal object WebLabCatalog {
    val games: List<GameDefinition> = listOf(
        spec("kids-picture-pairs", "Picture Pairs", "Flip friendly picture cards and find matching pairs.", LevelId.Explorer, Category.Memory, "🃏", 1),
        spec("kids-light-patterns", "Light Patterns", "Watch bright tiles and tap the same pattern back.", LevelId.Explorer, Category.Memory, "🔲", 1),
        spec("kids-number-train", "Number Train", "Remember short number trains as they grow.", LevelId.Explorer, Category.Memory, "🚂", 1),
        spec("kids-arrow-trail", "Arrow Trail", "Follow and repeat a short trail of arrows.", LevelId.Explorer, Category.Memory, "➡️", 1),
        spec("kids-flash-count", "Flash Count", "Add small numbers that pop onto the screen.", LevelId.Explorer, Category.Memory, "✨", 1),
        spec("kids-friendly-faces", "Friendly Faces", "Study simple faces and spot them again.", LevelId.Explorer, Category.Memory, "🙂", 1),
        spec("kids-animal-odd-one", "Animal Odd One", "Find the picture that is different from the rest.", LevelId.Explorer, Category.Speed, "🐾", 1),
        spec("kids-find-the-star", "Find the Star", "Search a busy grid and tap the target quickly.", LevelId.Explorer, Category.Speed, "⭐", 1),
        spec("kids-fast-tap", "Fast Tap", "Tap as soon as the signal says go.", LevelId.Explorer, Category.Speed, "👆", 1),
        spec("kids-counting-sprint", "Counting Sprint", "Solve quick number facts before time runs out.", LevelId.Explorer, Category.Speed, "🔢", 1),
        spec("kids-bigger-number", "Bigger Number", "Choose the bigger number as fast as you can.", LevelId.Explorer, Category.Speed, "⚖️", 1),
        spec("kids-missing-shape", "Missing Shape", "Pick the shape that completes the picture.", LevelId.Explorer, Category.Spatial, "🔺", 1),
        spec("kids-next-in-line", "Next in Line", "Guess what comes next in a simple pattern.", LevelId.Explorer, Category.Spatial, "➡️", 1),
        spec("kids-picture-matrix", "Picture Matrix", "Complete a small visual puzzle.", LevelId.Explorer, Category.Spatial, "🧩", 2),
        spec("kids-mini-grid", "Mini Grid Logic", "Fill a tiny number grid using simple rules.", LevelId.Explorer, Category.Logic, "🔢", 2),
        spec("kids-tower-builder", "Tower Builder", "Move pieces carefully to rebuild the tower.", LevelId.Explorer, Category.Logic, "🗼", 2),
        spec("kids-shape-detective", "Shape Detective", "Crack bright shape-and-color patterns before the mystery tile appears.", LevelId.Explorer, Category.Logic, "🔺", 2),
        spec("kids-odd-toy-out", "Odd Toy Out", "Spot the one toy that does not fit the secret group rule.", LevelId.Explorer, Category.Logic, "🧸", 1),
        spec("kids-animal-line-up", "Animal Line-Up", "Tap animals into the right order by size, speed, or legs.", LevelId.Explorer, Category.Logic, "🐾", 2),
        spec("kids-puzzle-path", "Puzzle Path", "Read the arrow code and guide the robot to the flag.", LevelId.Explorer, Category.Logic, "🤖", 2),
        spec("kids-what-comes-next", "What Comes Next?", "Complete playful picture patterns and build a combo streak.", LevelId.Explorer, Category.Logic, "⭐", 1),
        spec("kids-color-repeat", "Color Repeat", "Watch colors flash and repeat the sequence.", LevelId.Explorer, Category.Focus, "🔴", 2),
        spec("kids-color-focus", "Color Focus", "Pick the color while ignoring the word.", LevelId.Explorer, Category.Focus, "🎨", 2),
        spec("kids-color-difference", "Color Difference", "Find the tile with the tiny color shade difference.", LevelId.Explorer, Category.Focus, "🌈", 2),
        spec("kids-hidden-picture", "Hidden Picture", "Find a target hiding in a playful scene.", LevelId.Explorer, Category.Focus, "🔎", 2),
        spec("kids-edge-watch", "Edge Watch", "Keep focus in the middle while spotting edge symbols.", LevelId.Explorer, Category.Focus, "👁", 2),
        spec("kids-dot-path", "Dot Path", "Connect items in the right order.", LevelId.Explorer, Category.Focus, "🧭", 2),
        spec("kids-focus-dot", "Focus Dot", "Track a moving dot and stay focused.", LevelId.Explorer, Category.Focus, "🎯", 2),
        spec("kids-word-pop", "Word Pop", "Read quick words and answer simple questions.", LevelId.Explorer, Category.Reading, "📖", 2),
        spec("kids-story-pictures", "Story Pictures", "Read a short story and remember the details.", LevelId.Explorer, Category.Reading, "📚", 2),
        spec("kids-word-sort", "Word Sort", "Put words into the best matching group.", LevelId.Explorer, Category.Reading, "💬", 2),
        spec("kids-quick-sort", "Quick Sort", "Sort words quickly by category.", LevelId.Explorer, Category.Reading, "🗂", 2),
        spec("kids-symbol-code", "Symbol Code", "Use a simple key to match symbols and numbers.", LevelId.Explorer, Category.Reading, "🔣", 2),
        spec("kids-back-match", "Back Match", "Notice when a position matches one seen before.", LevelId.Explorer, Category.Focus, "🧩", 2),
        spec("kids-two-things", "Two Things", "Watch words and shapes at the same time.", LevelId.Explorer, Category.Focus, "🎭", 2),
        spec("kids-turn-the-shape", "Turn the Shape", "Find the shape after it turns around.", LevelId.Explorer, Category.Spatial, "🔄", 2),

        spec("fast-reading", "Fast Reading Challenge", "Read at RSVP speed and answer comprehension questions.", LevelId.Challenger, Category.Reading, "📖", 3),
        spec("number-memory", "Number Memory", "Remember a growing sequence of digits.", LevelId.Challenger, Category.Memory, "🔢", 3),
        spec("pattern-memory", "Pattern Memory", "Recreate a pattern of highlighted grid cells.", LevelId.Challenger, Category.Memory, "🔲", 3),
        spec("stroop-test", "Color-Word Conflict", "Click the ink color, not the word meaning. Stroop test.", LevelId.Challenger, Category.Focus, "🎨", 3),
        spec("dual-nback", "Dual N-Back", "Press when current position matches N steps ago.", LevelId.Challenger, Category.Focus, "🧩", 4),
        spec("mental-math", "Mental Math Sprint", "Solve as many math problems as possible in 60 seconds.", LevelId.Challenger, Category.Speed, "🧮", 3),
        spec("missing-shape", "Missing Shape", "Find the missing piece from the visual pattern.", LevelId.Challenger, Category.Spatial, "🔮", 3),
        spec("matrix-reasoning", "Matrix Reasoning", "Complete the matrix. Like Raven's progressive matrices.", LevelId.Challenger, Category.Spatial, "🧠", 4),
        spec("rotation-puzzle", "Rotation Puzzle", "Identify which rotation matches the original shape.", LevelId.Challenger, Category.Spatial, "🔄", 3),
        spec("odd-one-out", "Odd One Out", "Find the one emoji that doesn't belong in the grid.", LevelId.Challenger, Category.Speed, "🔍", 3),
        spec("sequence-prediction", "Sequence Prediction", "Predict the next item in number or letter sequences.", LevelId.Challenger, Category.Spatial, "📈", 3),
        spec("memory-cards", "Memory Cards", "Classic flip-and-match card pairs game.", LevelId.Challenger, Category.Memory, "🃏", 3),
        spec("flash-calculation", "Flash Calculation", "Sum numbers that flash briefly on screen.", LevelId.Challenger, Category.Memory, "⚡", 3),
        spec("peripheral-vision", "Peripheral Vision", "Click edge symbols while keeping eyes on the center.", LevelId.Challenger, Category.Focus, "👁", 4),
        spec("visual-search", "Visual Search", "Find the target letter hidden among hundreds of others.", LevelId.Challenger, Category.Speed, "🎯", 3),
        spec("simon-game", "Simon Game", "Repeat the growing color sequence.", LevelId.Challenger, Category.Focus, "🔴", 3),
        spec("reaction-time", "Reaction Time Test", "Click as fast as possible when the screen turns green.", LevelId.Challenger, Category.Speed, "⏱", 3),
        spec("multi-task", "Multi-Task Challenge", "Count shapes while reading words simultaneously.", LevelId.Challenger, Category.Focus, "🎭", 4),
        spec("word-association", "Word Association Speed", "Choose the best category for each stimulus word.", LevelId.Challenger, Category.Reading, "💬", 3),
        spec("story-recall", "Story Recall", "Read a short story then answer memory questions.", LevelId.Challenger, Category.Memory, "📚", 3),
        spec("symbol-digit", "Symbol Digit Coding", "Use the key to decode as many symbols as possible.", LevelId.Challenger, Category.Reading, "🔣", 3),
        spec("hidden-object", "Hidden Object Challenge", "Find the hidden object among a busy emoji scene.", LevelId.Challenger, Category.Focus, "🔎", 3),
        spec("direction-memory", "Direction Memory", "Memorize and repeat the arrow direction sequence.", LevelId.Challenger, Category.Memory, "🧭", 3),
        spec("rapid-categ", "Rapid Categorization", "Categorize words as fast as possible in 45 seconds.", LevelId.Challenger, Category.Reading, "🗂", 3),
        spec("sudoku-mini", "Sudoku Mini", "Fill the 4×4 Sudoku grid with logic.", LevelId.Challenger, Category.Logic, "🔢", 3),
        spec("tower-logic", "Tower Logic", "Move all discs to peg C in minimum moves.", LevelId.Challenger, Category.Logic, "🗼", 4),
        spec("trail-making", "Trail Making Test", "Connect numbers (Part A) or alternate 1-A-2-B (Part B).", LevelId.Challenger, Category.Focus, "🗺", 3),
        spec("face-memory", "Face Memory", "Study six faces then identify them among new ones.", LevelId.Challenger, Category.Memory, "😊", 3),
        spec("focus-timer", "Focus Timer", "Keep your cursor on the moving dot for 90 seconds.", LevelId.Challenger, Category.Focus, "🎯", 3),
        spec("speed-comparison", "Speed Comparison", "Click the larger of two numbers as fast as possible.", LevelId.Challenger, Category.Speed, "⚖", 3),
        spec("equation-relay", "Equation Relay", "Carry a value through a rapid chain of mental operations.", LevelId.Challenger, Category.Speed, "ER", 4),
        spec("target-number-forge", "Target Number Forge", "Read brackets and operation order to hit an exact target.", LevelId.Challenger, Category.Speed, "24", 4),
        spec("inference-rush", "Inference Rush", "Read dense micro-passages and infer the unstated conclusion.", LevelId.Challenger, Category.Reading, "IR", 4),
        spec("keyword-crossfire", "Keyword Crossfire", "Scan and compare two texts to find the decisive detail.", LevelId.Challenger, Category.Reading, "AB", 4),
        spec("advanced-logic-grid", "Advanced Logic Grid", "Use layered clues to assign each item exactly once.", LevelId.Challenger, Category.Logic, "ALG", 4),
        spec("logic-bridge", "Logic Bridge", "Choose every tile that satisfies the bridge rule.", LevelId.Challenger, Category.Logic, "LB", 3),
        spec("code-breaker", "Code Breaker", "Crack a short number code using exact and misplaced clues.", LevelId.Challenger, Category.Logic, "CB", 4),
        spec("switch-circuit", "Switch Circuit", "Toggle inputs to make AND, OR, and XOR gates hit the target.", LevelId.Challenger, Category.Logic, "SC", 4),
        spec("truth-detective", "Truth Detective", "Use statements to find the single truth-teller.", LevelId.Challenger, Category.Logic, "TD", 4),
        spec("grid-lock", "Grid Lock", "Place colors in a grid while obeying touching constraints.", LevelId.Challenger, Category.Logic, "GL", 4),
        spec("constraint-maze", "Constraint Maze", "Plan a route through walls while collecting required keys.", LevelId.Challenger, Category.Spatial, "CM", 4),
        spec("operation-switch", "Operation Switch", "Rapidly switch rules across arithmetic and comparison tasks.", LevelId.Challenger, Category.Focus, "OS", 4),
        spec("spatial-stack", "Spatial Stack", "Mentally stack rotations and infer the final direction.", LevelId.Challenger, Category.Spatial, "SS", 4),
        spec("analogies-pro", "Analogies Pro", "Solve dense verbal analogies under pressure.", LevelId.Challenger, Category.Reading, "AP", 4),

        spec("seniors-advanced-matrix", "Advanced Matrix Reasoning", "Complete tougher visual matrices using abstract rules.", LevelId.Thinker, Category.Spatial, "🧠", 5),
        spec("seniors-abstract-completion", "Abstract Completion", "Infer the missing part of a visual reasoning pattern.", LevelId.Thinker, Category.Spatial, "🔮", 5),
        spec("seniors-complex-sequences", "Complex Sequences", "Predict the next value in mixed logic sequences.", LevelId.Thinker, Category.Spatial, "📈", 4),
        spec("seniors-mental-rotation", "Mental Rotation", "Rotate forms mentally and identify the match.", LevelId.Thinker, Category.Spatial, "🔄", 5),
        spec("seniors-logic-grid", "Logic Grid", "Use constraints to complete a compact logic grid.", LevelId.Thinker, Category.Logic, "🔢", 5),
        spec("seniors-planning-tower", "Planning Tower", "Plan efficient moves through a tower puzzle.", LevelId.Thinker, Category.Logic, "🗼", 5),
        spec("seniors-digit-span", "Digit Span Challenge", "Hold longer digit strings in working memory.", LevelId.Thinker, Category.Memory, "🔢", 5),
        spec("seniors-spatial-span", "Spatial Span", "Recall increasingly complex spatial patterns.", LevelId.Thinker, Category.Memory, "🔲", 5),
        spec("seniors-card-recall", "Card Recall", "Match cards while minimizing memory errors.", LevelId.Thinker, Category.Memory, "🃏", 4),
        spec("seniors-running-sum", "Running Sum", "Track fast numbers and keep a mental total.", LevelId.Thinker, Category.Memory, "⚡", 4),
        spec("seniors-route-memory", "Route Memory", "Remember and reproduce direction routes.", LevelId.Thinker, Category.Memory, "🧭", 4),
        spec("seniors-face-recognition", "Face Recognition", "Study subtle face patterns and recognize them later.", LevelId.Thinker, Category.Memory, "🙂", 5),
        spec("seniors-dual-nback", "Dual N-Back", "Track position matches across working-memory steps.", LevelId.Thinker, Category.Focus, "🧩", 5),
        spec("seniors-inhibition-control", "Inhibition Control", "Suppress the word meaning and respond to color.", LevelId.Thinker, Category.Focus, "🎨", 5),
        spec("seniors-divided-attention", "Divided Attention", "Manage two streams of information at once.", LevelId.Thinker, Category.Focus, "🎭", 5),
        spec("seniors-trail-switching", "Trail Switching", "Connect alternating targets with flexible attention.", LevelId.Thinker, Category.Focus, "🗺", 5),
        spec("seniors-visual-scan", "Visual Scan", "Search dense scenes with careful visual control.", LevelId.Thinker, Category.Focus, "🔎", 4),
        spec("seniors-sustained-focus", "Sustained Focus", "Maintain precision on a moving target.", LevelId.Thinker, Category.Focus, "🎯", 5),
        spec("seniors-reaction-benchmark", "Reaction Benchmark", "Measure response speed across multiple trials.", LevelId.Thinker, Category.Speed, "⏱", 4),
        spec("seniors-symbol-search", "Symbol Search", "Find targets in dense visual arrays.", LevelId.Thinker, Category.Speed, "🎯", 4),
        spec("seniors-math-fluency", "Math Fluency", "Solve arithmetic rapidly with accuracy.", LevelId.Thinker, Category.Speed, "🧮", 4),
        spec("seniors-number-comparison", "Number Comparison", "Compare larger values under time pressure.", LevelId.Thinker, Category.Speed, "⚖️", 4),
        spec("seniors-visual-discrimination", "Visual Discrimination", "Spot the subtle outlier in a busy field.", LevelId.Thinker, Category.Speed, "🔍", 5),
        spec("seniors-equation-relay", "Equation Relay", "Carry values through multi-step mental arithmetic at speed.", LevelId.Thinker, Category.Speed, "ER", 5),
        spec("seniors-target-number-forge", "Target Number Forge", "Parse brackets and operation order to reach exact targets.", LevelId.Thinker, Category.Speed, "24", 5),
        spec("seniors-rapid-reading", "Rapid Reading", "Read quickly and answer comprehension checks.", LevelId.Thinker, Category.Reading, "📖", 4),
        spec("seniors-detail-recall", "Detail Recall", "Retain details from short written passages.", LevelId.Thinker, Category.Reading, "📚", 4),
        spec("seniors-semantic-speed", "Semantic Speed", "Choose word relationships quickly and accurately.", LevelId.Thinker, Category.Reading, "💬", 4),
        spec("seniors-category-fluency", "Category Fluency", "Classify words under speed pressure.", LevelId.Thinker, Category.Reading, "🗂", 4),
        spec("seniors-coding-speed", "Coding Speed", "Translate symbols through a key with processing speed.", LevelId.Thinker, Category.Reading, "🔣", 5),
        spec("seniors-inference-rush", "Inference Rush", "Extract implied conclusions from timed micro-passages.", LevelId.Thinker, Category.Reading, "IR", 5),
        spec("seniors-keyword-crossfire", "Keyword Crossfire", "Compare paired texts and locate the decisive contrast.", LevelId.Thinker, Category.Reading, "AB", 5),
        spec("seniors-peripheral-control", "Peripheral Control", "Use broad attention without losing central focus.", LevelId.Thinker, Category.Focus, "👁", 5),
        spec("seniors-sequence-control", "Sequence Control", "Repeat longer color sequences with precision.", LevelId.Thinker, Category.Memory, "🔴", 5),

        spec("expert-memory-weave", "Expert Memory Weave", "Memorize ordered shape-color bindings under shrinking study time.", LevelId.Mastermind, Category.Memory, "EMW", 6),
        spec("expert-rule-matrix", "Expert Rule Matrix", "Find grid cells satisfying abstract row-column rules.", LevelId.Mastermind, Category.Logic, "ERM", 6),
        spec("expert-attention-split", "Expert Attention Split", "Switch between color and parity targets at speed.", LevelId.Mastermind, Category.Focus, "EAS", 6),
        spec("expert-rapid-proof", "Expert Rapid Proof", "Judge compact logical arguments as valid or invalid.", LevelId.Mastermind, Category.Reading, "ERP", 6),
        spec("expert-number-cipher", "Expert Number Cipher", "Infer hidden numeric rules from sparse examples.", LevelId.Mastermind, Category.Logic, "ENC", 6),
        spec("expert-logic-grid", "Expert Logic Grid", "Solve layered assignment clues with very limited checks.", LevelId.Mastermind, Category.Logic, "XLG", 6),
        spec("expert-code-breaker", "Expert Code Breaker", "Crack clue-based codes while balancing exact and misplaced signals.", LevelId.Mastermind, Category.Logic, "XCB", 6),
        spec("expert-switch-circuit", "Expert Switch Circuit", "Resolve tougher gate targets through precise switch logic.", LevelId.Mastermind, Category.Logic, "XSC", 6),
        spec("expert-grid-lock", "Expert Grid Lock", "Place constrained grid pieces without violating adjacency rules.", LevelId.Mastermind, Category.Logic, "XGL", 6),
        spec("expert-constraint-maze", "Expert Constraint Maze", "Plan a constrained route through denser maze logic.", LevelId.Mastermind, Category.Spatial, "XCM", 6),
        spec("expert-operation-switch", "Expert Operation Switch", "Switch rules quickly across arithmetic and comparison tasks.", LevelId.Mastermind, Category.Focus, "XOS", 6),
        spec("expert-spatial-stack", "Expert Spatial Stack", "Mentally stack longer rotations and infer the final direction.", LevelId.Mastermind, Category.Spatial, "XSS", 6),
        spec("expert-dual-nback", "Expert Dual N-Back", "Track position matches under heavier working-memory load.", LevelId.Mastermind, Category.Focus, "XNB", 6),
        spec("expert-math-sprint", "Expert Math Sprint", "Solve staged arithmetic with faster progression and accuracy pressure.", LevelId.Mastermind, Category.Speed, "XMS", 6),
        spec("expert-equation-relay", "Expert Equation Relay", "Track long arithmetic chains without writing intermediate values.", LevelId.Mastermind, Category.Speed, "XER", 6),
        spec("expert-target-forge", "Expert Target Forge", "Resolve subtle precedence traps under a speed bonus.", LevelId.Mastermind, Category.Speed, "X24", 6),
        spec("expert-inference-rush", "Expert Inference Rush", "Infer unstated causes from dense passages under a short clock.", LevelId.Mastermind, Category.Reading, "XIR", 6),
        spec("expert-keyword-crossfire", "Expert Keyword Crossfire", "Scan paired evidence and identify the deciding comparison.", LevelId.Mastermind, Category.Reading, "XAB", 6),
        spec("expert-matrix-reasoning", "Expert Matrix Reasoning", "Complete abstract matrix patterns with advanced rule combinations.", LevelId.Mastermind, Category.Spatial, "XMR", 6),

        spec("master-memory-orbit", "Master Memory Orbit", "Hold demanding shape-color sequences and recall precise positions.", LevelId.Genius, Category.Memory, "MMO", 7),
        spec("master-logic-tangle", "Master Logic Tangle", "Resolve dense rule matrices with high precision.", LevelId.Genius, Category.Logic, "MLT", 7),
        spec("master-proof-storm", "Master Proof Storm", "Classify tricky logic statements under pressure.", LevelId.Genius, Category.Reading, "MPS", 7),
        spec("master-cipher-ladder", "Master Cipher Ladder", "Climb difficult numeric ciphers with limited examples.", LevelId.Genius, Category.Logic, "MCL", 7),
        spec("master-attention-collapse", "Master Attention Collapse", "Survive rapid rule switching across color and number targets.", LevelId.Genius, Category.Focus, "MAC", 7),
        spec("master-logic-grid", "Master Logic Grid", "Brutal clue grids with minimal room for checking mistakes.", LevelId.Genius, Category.Logic, "MLG", 7),
        spec("master-truth-detective", "Master Truth Detective", "Untangle truth and contradiction cases under high precision pressure.", LevelId.Genius, Category.Logic, "MTD", 7),
        spec("master-code-breaker", "Master Code Breaker", "Deduce compact codes from sparse and misleading clue patterns.", LevelId.Genius, Category.Logic, "MCB", 7),
        spec("master-switch-circuit", "Master Switch Circuit", "Hit exact circuit outputs across harder gate combinations.", LevelId.Genius, Category.Logic, "MSC", 7),
        spec("master-grid-lock", "Master Grid Lock", "Solve dense placement constraints without forbidden contacts.", LevelId.Genius, Category.Logic, "MGL", 7),
        spec("master-sequence-control", "Master Sequence Control", "Predict complex symbolic and numeric sequences.", LevelId.Genius, Category.Spatial, "MSQ", 7),
        spec("master-mental-rotation", "Master Mental Rotation", "Resolve rotations with minimal visual certainty.", LevelId.Genius, Category.Spatial, "MMR", 7),
        spec("master-coding-speed", "Master Coding Speed", "Translate dense symbol codes at high speed with few errors.", LevelId.Genius, Category.Reading, "MCS", 7),
        spec("master-divided-attention", "Master Divided Attention", "Manage simultaneous streams with extreme focus demands.", LevelId.Genius, Category.Focus, "MDA", 7),
        spec("master-peripheral-control", "Master Peripheral Control", "Keep central focus while processing difficult edge targets.", LevelId.Genius, Category.Focus, "MPC", 7),
        spec("master-equation-relay", "Master Equation Relay", "Survive eight-step mental arithmetic relays at maximum speed.", LevelId.Genius, Category.Speed, "MER", 7),
        spec("master-target-forge", "Master Target Forge", "Distinguish near-identical expressions with exact precedence.", LevelId.Genius, Category.Speed, "M24", 7),
        spec("master-inference-rush", "Master Inference Rush", "Extract implications from dense text in only seconds.", LevelId.Genius, Category.Reading, "MIR", 7),
        spec("master-keyword-crossfire", "Master Keyword Crossfire", "Compare competing evidence with ruthless scanning speed.", LevelId.Genius, Category.Reading, "MAB", 7),
    )

    private fun spec(
        id: String,
        name: String,
        description: String,
        level: LevelId,
        category: Category,
        icon: String,
        difficulty: Int,
    ): GameDefinition {
        val tags = (when (category) {
            Category.Math -> listOf("math", "numbers", "calculation")
            Category.Memory -> listOf("memory", "visual", "sequence")
            Category.Logic -> listOf("logic", "patterns", "planning")
            Category.Reading -> listOf("reading", "words", "comprehension")
            Category.Focus -> listOf("focus", "attention", "timed")
            Category.Spatial -> listOf("spatial", "visual", "rotation")
            Category.Speed -> listOf("speed", "reaction", "focus")
        } + "web-lab" + when (level) {
            LevelId.Explorer -> "kids"
            LevelId.Challenger -> "beginner"
            LevelId.Thinker -> "advanced"
            LevelId.Mastermind -> "expert"
            LevelId.Genius -> "master"
        }).distinct().take(6)
        return GameDefinition(
            id = id,
            name = name,
            description = description,
            level = level,
            category = category,
            tags = tags,
            difficulty = difficulty,
            durationMinutes = 3 + difficulty.coerceAtMost(4),
            minAge = 6 + level.ordinal * 2,
            icon = icon,
            accent = level.accent,
            instructions = "Play the native $name board: watch, tap, swipe or lock answers just like the web lab.",
            scoringModel = "Correct answers, accuracy, response speed and combo bonuses increase the final score.",
            xpReward = 80 + level.ordinal * 20,
            unlockRequirement = if (level.minXp == 0) "Available immediately" else "Unlocks at ${level.minXp} XP",
            bestScoreType = BestScoreType.HigherIsBetter,
            status = ImplementationStatus.Playable,
            accessibilityNotes = "Large native controls, TalkBack labels, pause support and no color-only rules.",
        )
    }
}
